{
 "title": "API",
 "description": "Show all incoming api requests (what endpoints and how much)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "latency",
   "type": "timeseries",
   "description": "http request latency",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\n    sum by (le) (rate(http_server_request_duration_milliseconds_bucket[30s]))\n  )",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90,\n    sum by (le) (rate(http_server_request_duration_milliseconds_bucket[30s]))\n  )",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95,\n    sum by (le) (rate(http_server_request_duration_milliseconds_bucket[30s]))\n  )",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99,\n    sum by (le) (rate(http_server_request_duration_milliseconds_bucket[30s]))\n  )",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "http active connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_server_active_connections{otel_scope_name=\"duo.api\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "rpc calls latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\n    sum by (le) (rate(grpc_client_request_duration_milliseconds_bucket[30s]))\n  )",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90,\n    sum by (le) (rate(grpc_client_request_duration_milliseconds_bucket[30s]))\n  )",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95,\n    sum by (le) (rate(grpc_client_request_duration_milliseconds_bucket[30s]))\n  )",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99,\n    sum by (le) (rate(grpc_client_request_duration_milliseconds_bucket[30s]))\n  )",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "req/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by (path) (rate(http_server_request_count_total{otel_scope_name=\"duo.api\"}[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "rpc call rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (method) (rate(grpc_client_request_count_total[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request / Response I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_size_by_sum{otel_scope_name=\"duo.api\"}[30s]))",
     "legendFormat": "in"
    },
    {
     "expr": "sum(rate(http_server_response_size_by_sum{otel_scope_name=\"duo.api\"}[30s]))",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Statuses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(status) (rate(http_server_request_count_total{otel_scope_name=\"duo.api\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}