{
 "title": "Game Service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "response statuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (code) (rate(grpc_server_request_count_total{otel_scope_name=\"duo.game\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(grpc_server_request_duration_milliseconds_bucket{otel_scope_name=\"duo.game\"}[30s])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(grpc_server_request_duration_milliseconds_bucket{otel_scope_name=\"duo.game\"}[30s])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(grpc_server_request_duration_milliseconds_bucket{otel_scope_name=\"duo.game\"}[30s])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "req/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(method) (rate(grpc_server_request_count_total{otel_scope_name=\"duo.game\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}