{
 "title": "Websockets",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "disconnection rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (path) (rate(ws_server_disconnection_count_total{otel_scope_name=\"duo.api\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "active connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (path) (ws_server_connection_active)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "messages sent/recv",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum (rate(ws_server_message_sent_total[30s]))",
     "legendFormat": "sent"
    },
    {
     "expr": "sum (rate(ws_server_message_received_total[30s]))",
     "legendFormat": "recv"
    }
   ]
  },
  {
   "title": "connections rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by (path) (rate(ws_server_connection_count_total{otel_scope_name=\"duo.api\"}[30s]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(ws_server_message_size_by_sum{direction=\"in\"}[30s]))",
     "legendFormat": "in"
    },
    {
     "expr": "sum(rate(ws_server_message_size_by_sum{direction=\"out\"}[30s]))",
     "legendFormat": "out"
    }
   ]
  }
 ]
}