name: checks-frontend

on:
  push:
    branches: [main]
    tags: ['*']
    paths: ['services/ui/**']
  pull_request:
    branches: [main]
    paths: ['services/ui/**', '.github/workflows/frontend-ci.yml']

jobs:
  checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/ui

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v5
        with:
          version: 10  

      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: services/ui/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format
        run: pnpm format:check

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test

  build:
    runs-on: ubuntu-latest
    needs: [checks]
    if: startsWith(github.ref, 'refs/tags/')
    defaults:
      run:
        working-directory: services/ui

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v5
        with:
          version: 10  

      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: services/ui/pnpm-lock.yaml

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: copy env
        run: cp .env.prod .env

      - name: build project
        env:
          VITE_SENTRY_DSN: ${{ secrets.UI_SENTRY_DSN }}
          VITE_SENTRY_ENVIRONMENT: production
          VITE_SENTRY_RELEASE: ${{ github.ref_name }}
        run: pnpm run build

      - name: save build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: frontend-dist
          path: services/ui/dist/

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: download build
        uses: actions/download-artifact@v7
        with:
          name: frontend-dist
          path: dist/

      - name: setup ssh key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: sync files
        run: |
          rsync -az \
          --delete \
          dist/ \
          ${{ secrets.SERVER_USER }}@${{secrets.SERVER_HOST }}:/var/www/duo/
